name: Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: "Read NodeJS Version"
        id: read-nodejs-version
        uses: pCYSl5EDgo/cat@cde404f088c582552b0fe4e24ecb3159445fde2a
        with:
          path: ./.node-version
          trim: true
      - name: Setup NodeJS
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: ${{ steps.read-nodejs-version.outputs.text }}
      - name: Cache Dependencies
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
        with:
          path: ~/.npm/
          key: npm-cache-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}-${{ steps.read-nodejs-version.outputs.text }}
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
